// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi6U1Pbp8ke7u4bVv6VF8ua-DIfdXYm7M',
    appId: '1:442275087370:web:d1ef9846f34d869fa70bf3',
    messagingSenderId: '442275087370',
    projectId: 'chat-app-23da1',
    authDomain: 'chat-app-23da1.firebaseapp.com',
    storageBucket: 'chat-app-23da1.appspot.com',
    measurementId: 'G-LGER0SFWPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoyFDUn6xO6R3bHn84JA-bN9u_GHabwqY',
    appId: '1:442275087370:android:a52c627836022cdfa70bf3',
    messagingSenderId: '442275087370',
    projectId: 'chat-app-23da1',
    storageBucket: 'chat-app-23da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8PF3oAqtUxSTOvgNwrzY3BUldPAPxD1Q',
    appId: '1:442275087370:ios:f1151cf395d4a161a70bf3',
    messagingSenderId: '442275087370',
    projectId: 'chat-app-23da1',
    storageBucket: 'chat-app-23da1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8PF3oAqtUxSTOvgNwrzY3BUldPAPxD1Q',
    appId: '1:442275087370:ios:f2013d84d93e053ea70bf3',
    messagingSenderId: '442275087370',
    projectId: 'chat-app-23da1',
    storageBucket: 'chat-app-23da1.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
